//--------------------------------------------------------------------------------------------------------------
// KU-HEP
// root script file for pxar test
// Jack W King III
// -------------------------------------------------------------------------------------------------------------       
//   script entry point commands begin on line 687
//   scripts for BB vs PA for generic file convention on line 894
//  ------------------ new work: line 647------------------------------------------------------
//--------------------------------------------------------------------------------------------------------------
/*

//------------------------------------------------------------------------------------------------------------------------------------
//-----------------------------------------------------  start of scripts ------------------------------------------------------------
//-------------------------------  KU convention assumed for first section -----------------------------------------------------------
//------------------------------------------------------------------------------------------------------------------------------------
// --   scripts --  designed to loop through all chips in a module with minimal input
// --  assumed that root is ran from within the folder with the TFiles in question.
//------------------------------------------------------------------------------------------------------------------------------------

// returns bad for a chip if any pixles in the chip are below a threshold of 8
// on the pixel Alive test. llops through all chips on module

bool validpa( string module )
Valid Pixel Alive Graph? - module is the module name assuming KU file suffexes as below

bool validxray( string module )
Valid Xray Graph? - module is the module name assuming KU file suffexes as below
--------------------------------------------------------------------------------------------
// compares bumpbond vs pixel alive map and returns a 4 value map
// it first uses a threshold valueof 8 on PA to determine if pixel good/bad
// it then set all pixels over 2 sigma on BB as bad, under good
// compares the result pixel by pixel and returns a new map that 
// shows if both bad, both good, or the two cases of only one good
// loops through all chips on module

void cpxrcomp( string module )
composite graph vs Xray(DAQ) graph comparision

void bbpacomp( string module  )
bumpbond graph vs pixelalive graph compariosion

void xrhreff( string hreffdirfile )
Xray high rage effeciancy -- assumes all DAQ graphs present c0 - c15
input is hgh range effecancy directory file name for DAQ results
// to see if the are the same -- used for repeat runs of same module

void mmcomp( string amodule, string bmodule, string dir, string mapfile )
map to map comparision input 
// same as above for all chips on a module

void multimmcomp( string amodule, string bmodule, string dir, string mapfile  )
multiple map to map comparisions  
//  pulls good vs bad pixels and distributions of data for the BumpBond test
// for all chips on module.  assumes each chip has its own TFile

void bbstats( string bbdirfile, int chip )--  where there is one chip per dir file
Bumpbond test result statitics  co - c15 in seperate files

void bbstats( string bbdirfile )-- where there is one dir file for all chips
Bump bond test result statistics C0-c15 in one file

// runs all four base comparision tests on a single module

void runcomptests( string module )
runs all tests on module files in folder if file names set up correctlly

//---------------------------------------------------------------------------------------------------------------------
//---- Generic scripts to run BumpBond vs PixelAlive ------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------

// bumpbond directory and pixel alive directory files ( .root files ) must be in same directory the script is ran from
// bbdirname and padirbname are the name of the TFiles generated by pxar.  If additional subdirectories have been added 
// to the directory files then specify in bbsubfolder and pasubfolder.  Chip is the chip number that you want to 
// compare the Bumpbond and PixelAlive map histograms for.

void comparebbvspa( string bbdirname, string padirname, int chip )
Compare Bump Bond vs Pixel Alive based on Bump bond directory file name, PixelAlive directory file name and chip number
-- ASSUMES no additional sub directoties added to the TFile,  if additional subdirecotries added use below function with subdirectory
folders specifed in bbsubfolder and pasubfolder....

void comparebbvspa( string bbdirname, string bbsubfolder, string padirname, string pasubfolder, int chip )

 */
//----------------------------------------------------------------------------------------------------------------
#ifndef ROOTSTD                                     
#include "TCanvas.h"
#include "TGraphErrors.h"
#include "TFile.h"
#include"TF1.h"
#include"TCanvas.h"
#include"TH1.h"
#include"TH2.h"
#include"TLegend.h" 
#include"TArrow.h"
#include"TLatex.h" 
#include"TDirectory.h"
#define ROOTSTD
#endif

#include"strFunLib.cpp"          // personal libary

#ifndef CSTD
#include <cstdlib>
#include <cstdio>
#include <cmath>
#include <cstring>
#include <string>
#include <iostream>
#include <fstream>
#include <iomanip>
#include <ctime>
#define CSTD
#endif

//#defineTESTSCPT

//--------------String Constants--------------------------------------------------------------------------------
//----------------------------------------------------------------------------------------------------------------------
//module names
const string bslash("/");
const string modCR919("M_CR_919");       // example of KU Module name convention
const string modCR919R("M_CR_919_R");    
//test runs dirctories and files -- examples if KU naming conventions
const string bbfiletem("BumpBonding/thr_calSMapXtalk_VthrComp_C14_V0");
const string papamap("PixelAlive/PixelAlive_C14_V0");
const string bbdirfiletemp("M_CR_919_BB_C14.root"); 
const string padirfiletemp("M_CR_919_Pretest_Alive.root");
//pxar file names for bumpbond and pixel alive and my internal file names 
// named by tester means names not set by pxar or this script and may vary
const string bbxtfile("thr_calSMapXtalk_VthrComp_C_V0");//26
const string bbfile("thr_calSMap_VthrComp_C_V0");//21
const string bbdistfile("dist_thr_calSMap_VthrComp_C_V0");//28
const string bbdir("_BB_C.root");//5--named by tester:  ku convention: module_name + bbdir + chip_num
const string pafile("PixelAlive_C_V0");//11
const string padir("_Pretest_Alive.root");//--named by tester: ku convention: module_name + padir
const string bbsubdir("BumpBonding/");
const string pasubdir("PixelAlive/");
const string cpdir("_BBPAComp.root");
const string cpxrdir("_CPXRComp.root");
const string xrdir("_xray_20M.root");//--named by tester: robert convention: module_name + xrdir(robert names)
//const string xrdir("_XRay_Combined.root");//--named by tester: KU convention as above ( jackson names)
//const string cpfile("_BB_C_vs_PA");replaced by bbpacompmap
const string xrfile("Hits_C_V0");

//const string xrfile("hits_C_V0");
const string xrsubdir("DAQ/");
const string bbpacompmap("BBPACompMap_C");
const string cpxrcompmap("CPXRCompMap_C");

//files names for bad pixels stats 

const string paValidText("_PA_Valid.txt");c++ tab in a string
const string xrValidText("_XR_Valid.txt");
const string bbpaBadPixsText("_BBvsPA_BadPixs.txt"); 
const string bbDistroText("_BBDistros.txt");
const string genericBBvsPAText("BBvsPA_BadPixs.txt");
const string genericBBvsPAModuleName("BBvsPAMapComp_C");
const string cpxrPixsStatsText("_CPvsXR_BadPixs.txt");

//file names for unformated bad pixels lists 
const string badBBvsPAList("_BBvsPABadPixelsList.txt");
const string badCPvsXRList("_CPvsXRBadPixelsList.txt");
const string badPAList("_PixelAliveBadPixelsList.txt");

//--------------------Interger Constants-----------------------------------------------------------------
//------------------------------------------------------------------------------------------------------------------
const int NUMROWS = 51;
const int NUMCOLS = 83;
const int PAGOODTHRESHOLD = 8;
const int MAXPIXS = 4200;
const int PIXCELLS = 4160;
const int BADBUMPBOND = 2;
const int BADPIXCELL = 1;
const double WIDTHVTHRESCOMP = 2.5;
//levels for 4 level results of binary hisc++ tab in a stringtogram comparision
const int PAB = 8;// also bad on xray and good on cp
const int BBB = 4;// also bad on cp and good on xray
const int BOTHB = 1;// bad on both
const int BOTHG = 12;//good on both
//start and end of bins that contian pixel data..  excludes overflow bins.
const int RS = 1;//row start
const int RE = 53;//row end
const int CS = 1;//col start
const int CE = 81;//col end

//--------------data structures---------------------------------------------------------------
//-----------------------------------------------------------------------------------------------------

struct bbData { 
  double mean, bad, stdev, sum;
  double prb0, prbm, prb1, prb2, prb3;
  int zero, sum1, sum2, sum3, max;
};


struct pixCell{
  int chip;
  int row;
  int col;
  double data;
};

class  pixChip{
private:
  pixCell cell[ MAXPIXS ];
  int count;
  
public:

  void pixChip::pixChip( ){
    
    //    cout << "Initilizing pixChip" << endl;
    for( int num = 0; num < MAXPIXS; num++){
      cell[num].chip = -1;
      cell[num].row = -1;
      cell[num].col = -1;
      cell[num].data = -1;
    }
    count = 0;
    //    cout << "pixChip Initialized." << endl;
    return;
  }
  
    void pixChip::zeroChip( ){
    
    //    cout << "Initilizing pixChip" << endl;
    for( int num = 0; num < MAXPIXS; num++){
      cell[num].chip = -1;
      cell[num].row = -1;
      cell[num].col = -1;
      cell[num].data = -1;
    }
    count = 0;
    //    cout << "pixChip Initialized." << endl;
    return;
  }
  
  void pixChip::setCellRow( int cellnum, int rownum ){

    cell[cellnum].row = rownum;

    return;
  }

  void pixChip::setCellCol( int cellnum, int colnum ){

    cell[cellnum].col = colnum;
    return;
  }

  void pixChip::setCellData( int cellnum, int datanum ){

    cell[cellnum].data = datanum;
    return;
  }

	void pixChip::setCount( int number ){
	
		count += number;
		return;
	}

  void pixChip::setCell( int cellnum, int rownum, int colnum, int datanum ){

    cell[cellnum].chip = 999;
    cell[cellnum].row = rownum;
    cell[cellnum].col = colnum;
    cell[cellnum].data = datanum;
    return;
  }

  pixCell pixChip::getCell( int cellnum ){

    return cell[cellnum];
  }

	int pixChip::getCount(){

		return count;
	}

	int pixChip::clearCount(){

		count = 0;
		return;
	}

  void pixChip::setCell( int cellnum, int chipnum,  int rownum, int colnum, int datanum ){

    cell[cellnum].chip = chipnum;
    cell[cellnum].row = rownum;
    cell[cellnum].col = colnum;
    cell[cellnum].data = datanum;
    return;
  }

  void pixChip::printCell( pixCell cell, ofstream& out ){

    out << "Chip: " << cell.chip  << "Cell: " << cell.row << " : " << cell.col << " Value: " << cell.data << endl;
    return;
  }

  void pixChip::printCell( int cellnum, ofstream& out ){

    out << "Chip: " << cell[cellnum].chip << "Cell: " << cell[cellnum].row << " : " << cell[cellnum].col << " Value: " << cell[cellnum].data << endl;
    return;
  }

  void pixChip::printChip( ofstream& out ){
    cout << "In Print Cell ";
    for( int cellnum = 0; cellnum < MAXPIXS; cellnum++){
      //   cout << cell ;
      printCell( cell[cellnum], out );
    }
    //  cout << endl;
    return; 
  }

  void pixChip::printCellsWithDataOnChip( ofstream& out ){
    
    for( int cellnum = 0; cellnum < MAXPIXS; cellnum++){
      if( cell[cellnum].chip > -1 ) printCell( cell[cellnum], out );
    }
    return; 
  }

  void pixChip::printCellsWithDataUnformated( ofstream& out){
    
    cout << " Print cells" << endl;
    for( int i = 0; i < MAXPIXS; i++){
      if( cell[i].chip > -1 ){
				cout << i << " ";
				out << cell[i].chip << " " << cell[i].row << " " << cell[i].col << " " << cell[i].data << endl;
      }
     // cout << endl;
    }
    return;
  }
  
};

//-------------- Helper Functions----------------------------------------------------------
//--------------------------------------------------------------------------------------------------
int openInStream( string fileName, ifstream& in ){
  
  char* temp = new char[ fileName.length() + 1 ];
  strcpy( temp, fileName.c_str() );
  in.open( temp );
  if( in.is_open() ){ return 1;}

  else return 0; 

}

int openOutStream( string fileName, ofstream& out ){
  
  char* temp = new char[ fileName.length() + 1 ];
  strcpy( temp, fileName.c_str() );
  out.open( temp );
  if( out.is_open() ){ return 1;}
  else return 0;

}

//----------------------------------------------------------------------------------------------------
double myGetMean( TH2D* hist ){
  
  double sum = 0, count = 0;
  
  for( int row = RS; row < RE; row++ ){
    for( int col = CS; col < CE; col++){
      sum += hist->GetBinContent( row, col );
      count++;

    }
  }
  return sum/count;
}

double myGetStdDev( TH2D* hist, double mean ){
  
  double sum = 0, count =0;
  
  for( int row =RS; row<RE; row++){
    for( int col =CS; col<CE; col++){
      sum += pow( ( hist->GetBinContent( row, col ) - mean ), 2);
      count++;
    }
  } 
  return sqrt( sum/count );
}

double myGetSamDev( TH2D* hist, double mean ){
  
  double sum = 0, count =0;
  
  for( int row =RS-1; row<RE+1; row++){
    for( int col =CS-1; col<CE+1; col++){
      sum += pow( ( hist->GetBinContent( row, col ) - mean ), 2);
      count++;
    }
  } 
  return sqrt( sum/( count - 1 ) );
}


double myGetStdErr( TH2D* hist, double mean ){
  
  double sum = 0, count =0, dev = 0;
  
  for( int row =RS-1; row<RE+1; row++){
    for( int col =CS-1; col<CE+1; col++){
      sum += pow( ( hist->GetBinContent( row, col ) - mean ), 2);
      count++;
    }
  } 
  dev = sqrt( sum/( count - 1  ));
  return dev/sqrt(count);
}
   
//-------------histogram modification and creation functions----------------------
//-------------------------------------------------------------------------------------------------------
TH2D* getBinaryZHist( TH2D *hist, double zee ){
  
//  cout << "In getBinaryHist  with " <<  hist << " and " << zee << endl;
  double mean, stdev, bbgood, bbraw, thresholdlow, thresholdhigh;
  
  mean = myGetMean( hist );
  stdev = myGetStdDev( hist, mean );
  
//  cout << "coping hist " << endl;
  TH2D *hbinary =  (TH2D*) hist->Clone();
  hbinary->SetName("Binary");

//  cout << hbinary << endl;
//  cout << mean << endl;
  thresholdlow = mean - zee*stdev;
//  cout << thresholdlow << endl;
  thresholdhigh = mean + zee*stdev;
//  cout << thresholdhigh << endl;
  
  for( int row =RS; row < RE; row++ ){
    for( int col =CS; col < CE; col++){
      bbraw = hist->GetBinContent( row, col );
      if( ( bbraw > thresholdlow ) && ( bbraw < thresholdhigh ) ) hbinary->SetBinContent( row, col, 1 );
      else hbinary->SetBinContent( row, col, 0 );
    }
  }
//  cout << "returning" << endl;
  return hbinary;
}


TH2D* getBinaryThresHist( TH2D *hist, double thres ){
  


//  cout << "In getBinaryHist  with " <<  hist << " all or nothing" << endl;
  double mean, stdev, bbgood, bbraw, thresholdlow, thresholdhigh;
    
//  cout << "coping hist " << endl;
  TH2D *hbinary =  (TH2D*) hist->Clone();
  hbinary->SetName("Binary");
//  cout << hbinary << endl;
  
  for( int row =RS; row < RE; row++ ){
    for( int col =CS; col < CE; col++){
      bbraw = hist->GetBinContent( row, col );
      if( bbraw > thres ) hbinary->SetBinContent( row, col, 1 );
      else hbinary->SetBinContent( row, col, 0 );
    }
  }
//  cout << "returning" << endl;
  return hbinary;
}

TH2D* getBinaryCompareMaps( TH2D *first, TH2D *second ){
  
//  cout << " coping first" << endl;
  TH2D *compHist = (TH2D*) first->Clone();
  
//  cout << "modifing plot - creating comp plot" << endl;
  double firstData, secondData;
  for( int row =RS; row < RE; row++ ){
    for( int col =CS; col < CE; col++){
      firstData = first->GetBinContent( row, col );
      secondData = second->GetBinContent( row, col );
      if(  firstData && secondData ) compHist->SetBinContent( row, col, BOTHG );
      else if ( firstData && ( ! secondData  ) ) compHist->SetBinContent( row, col, PAB );
      else if( ( ! firstData )  && secondData ) compHist->SetBinContent( row, col, BBB);
      else compHist->SetBinContent( row, col, BOTHB);
    }
  }
    
  return compHist;  
}

TH2D* getEqualCompMaps( TH2D *first, TH2D *second ){
  
//  cout << " coping first" << endl;
  TH2D *compHist = (TH2D*) first->Clone();
  
//  cout << "modifing plot - creating comp plot" << endl;
  double bbraw, paraw;
  
  for( int row =RS; row < RE; row++ ){
    for( int col =CS; col < CE; col++){
      bbraw = first->GetBinContent( row, col );
      paraw = second->GetBinContent( row, col );
      if(  bbraw ==  paraw ) compHist->SetBinContent( row, col, 1 );
      else compHist->SetBinContent( row, col, 0 );
    }
  }
  return compHist;  
}

//---------------------------single file vs single file comparisions------------------------------
//------------------------------------------------------------------------------------------------

bool pixAliveGood( TH2D *pahist, pixChip& bads ){ 
  
  double paraw;

  bool result = true;
  int cell = 0;
   
  for( int row =RS; row < RE; row++ ){
    for( int col =CS; col < CE; col++){
      paraw = pahist->GetBinContent( row, col );
      // cout << paraw <<" ";
      if( paraw >= PAGOODTHRESHOLD  ){ result = result && true; }
      else{
				result = result && false;
				bads.setCell( cell, row, col, paraw );
				bads.setCount( 1 );
				cell++;
      }
    }
  }
  //cout << result << endl;
  return result; 
}


bool xRayThreshold( TH2D *xrhist, ofstream& out, pixChip& bads ){ 
  
  out << ": Checking values vs threshold : " ;
  double xrraw;
  bool result = true;
  int cell = 0;
   
  for( int row =RS; row < RE; row++ ){
    for( int col =CS; col < CE; col++){
      xrraw = xrhist->GetBinContent( row, col );
      // cout << xrraw<<" ";
      if( xrraw > 1  ) result = result && true;
      else{
	result = result && false;
	bads.setCell( cell, row, col, xrraw );
	cell++;
      }
    }
    // cout << endl;
  }
  if( result ) out << "Chip is good"<<endl;
  else out << "Chip is Bad with "<< cell << " bad pix cells. " << endl;
  
  return result; 
}

TH2D* compXRCPMaps( string cpdirfile, string xrdirfile, string cphistfile, string xrhistfile ){
  
//  cout << "CompXRCPMaps called with:" << endl;
//  cout << cpdirfile << endl;
//  cout << xrdirfile << endl;
//  cout << cphistfile << endl;
//  cout << xrhistfile << endl;
     
//  cout << "opeaning in files" << endl;
  TFile *cpInFile = new TFile( strToChar( cpdirfile ) );
  TFile *xrInFile = new TFile( strToChar( xrdirfile ) );
//  cout << cpInFile << ":" << xrInFile << endl;  
  
//  cout << "creating plot files" << endl;
  TH2D *cpHist, *xrHist;
  cpInFile->GetObject( strToChar( cphistfile ), cpHist );
//  cout << cpHist << endl;
  xrInFile->GetObject( strToChar( xrhistfile ), xrHist );
//  cout << xrHist << endl;
  
//  cout << "Getting binaries:" << endl;
  TH2D *cpBinary, *xrBinary;
  cpBinary = getBinaryThresHist( cpHist, 9 );
  xrBinary = getBinaryThresHist( xrHist, 0 );
  
//  cout << " coping bbBinary" << endl;
  TH2D *compHist = (TH2D*) getBinaryCompareMaps( cpBinary, xrBinary );

  return compHist;  
}

TH2D*  compBBPAMap( string padirfile, string bbdirfile, string pahistfile, string bbhistfile ){

//  cout << "CompBBPAMaps called with:" << endl;
//  cout << padirfile << endl;
//  cout << bbdirfile << endl;
//  cout << pahistfile << endl;
//  cout << bbhistfile << endl;

//  cout << "opeaning in files" << endl;
  TFile *paInFile = new TFile( strToChar( padirfile ) );
  TFile *bbInFile = new TFile( strToChar( bbdirfile ) );

//  cout << paInFile << ":" << bbInFile << endl;  
  
//  cout << "creating plot files" << endl;
  TH2D *bbHist, *paHist;
  paInFile->GetObject( strToChar( pahistfile ), paHist );
//  cout << paHist << endl;
  bbInFile->GetObject( strToChar( bbhistfile ), bbHist );
//  cout << bbHist << endl;
  
//  cout << "Getting binaries:" << endl;
  TH2D *bbBinary, *paBinary;
  double mean, stdev;
  
  paBinary = getBinaryThresHist( paHist, PAGOODTHRESHOLD );
  bbBinary = getBinaryZHist( bbHist, WIDTHVTHRESCOMP  );
  
//  cout << " coping bbBinary" << endl;
  TH2D *compHist = (TH2D*) getBinaryCompareMaps( bbBinary, paBinary );

  return compHist;  
}

TH2D* compMapToMap( string padirfile, string bbdirfile, string pahistfile, string bbhistfile ){
   
//  cout << "CompMMMaps called with:" << endl;
  // cout << pamodule << endl;
  out << module << " CP vs XR Comparision Map" << endl;
  //cout << bbmodule << endl;
//  cout << padirfile << endl;
//  cout << bbdirfile << endl;
//  cout << pahistfile << endl;
//  cout << bbhistfile << endl;
  string outfile( pahistfile + "_vs_" + bbhistfile + ".root");
  //cout << "opening in Canvas" << endl;
  //TCanvas *can = new TCanvas( strToChar( bbdirfile + "_vs_PixelAlive") , "Pixel Map", 200,10,700,500 );
  //cout << can << endl;
//  cout << "opeaning in files" << endl;
  TFile *paInFile = new TFile( strToChar( padirfile ) );
  TFile *bbInFile = new TFile( strToChar( bbdirfile ) );
//  cout << paInFile << ":" << bbInFile << endl;
  
//  cout << "creating plot files" << endl;
  TH2D *bbHist, *paHist;
  paInFile->GetObject( strToChar( pahistfile ), paHist );
//  cout << paHist << endl;c++ tab in a string
  bbInFile->GetObject( strToChar( bbhistfile ), bbHist );
//  cout << bbHist << endl;
  
//  cout << " coping bbBinary" << endl;
  TH2D *compHist = (TH2D*) getEqualCompMaps( paHist, bbHist );
  compHist->SetNameTitle( strToChar( bbhistfile + "s_Equal" ) , "CompMap"); 
  TFile *outCompFile = new TFile( strToChar( outfile ), "UPDATE" );  
//  cout << "outfile is : " << outfile << ":" << outCompFile << endl;
//  cout << "writing histogram file" << endl;
  compHist->Write();
  outCompFile->Close();
  
//  cout << " returning"  << endl;
  return compHist;

}

pixChip  getBadBBPACompPixs( int chip, TH2D *binary, string module, ofstream& out ){
    
  double raw;
  double badpix = 0, badbond = 0;
  int num = 0;
  pixChip bads;

//  cout << "In getBadBBPACompPixs" << endl;
  for( int row =RS; row < RE; row++ ){
    for( int col =CS; col < CE; col++){
      raw = binary->GetBinContent( row, col );
      if( raw == BBB ){
				//cout << raw << " ";
				bads.setCell( num, chip,  row, col, BADBUMPBOND );
				num++;
				badbond++;
	//	cout << row << " " << col << " " << endl;
      } else if ( (raw == PAB )  ||  (raw == BOTHB )  ){

	//		cout << raw << " ";
	//		bads.setCell( num, chip, row, col, BADPIXCELL );
	//		num++;
	//		badpix++;
	//		cout << row << " " << col << " " << endl;
      }
    } 
  }   
  //out << module << " : BB PA Comparision Maps " << endl;
  out << "Bad BumpBonds: #: " << badbond << " %: "<< 100* badbond/(PIXCELLS) << endl;
  //  out <<  "Bad Pixel Cells: #: " << badpix << " %: " <<  100*badpix/(PIXCELLS) << endl;
  return bads; 
}
 
pixChip getBadCPXRCompPixs( int chip, TH2D *binary, string module, ofstream& out ){
    

  double raw;
  double badpix = 0, badbond = 0;
  int num = 0;
  pixChip bads;

 // cout << "In getBBPACompPixs" << endl;
  for( int row =RS; row < RE; row++ ){
    for( int col =CS; col < CE; col++){
       raw = binary->GetBinContent( row, col );
      if( raw == BBB ){
			//	cout << raw << " ";
				bads.setCell( num, chip, row, col, BADBUMPBOND );
				num++;
				badbond++;
	//	cout << row << " " << col << " " << endl;
      } else if ( raw == PAB ){
			//	cout << raw << " ";
				bads.setCell( num, chip, row, col,  BADPIXCELL );
				num++;
				badpix++;
	//	cout << row << " " << col << " " << endl;
      }
    } 
  }   
  //out << module << " : BB PA Comparision Maps " << endl;
  out << "Bad on CP map with Good Xray: #: " << badbond << " %: "<< 100* badbond/(PIXCELLS) << endl;
  out <<  "Bad on Xray map with Good CP: #: " << badpix << " %: " <<  100*badpix/(PIXCELLS) << endl;
  return bads; 
}
  
bbData getBBStats( string dirfile, string file ){
    
//  cout << " in getbbstats with " << endl;
//  cout << dirfile << endl;
 // cout << file << endl;
  TFile *infile = new TFile( strToChar( dirfile ) );
//  cout << infile << endl;
  TH1D *dist;
  infile->GetObject( strToChar( bbsubdir + file ) , dist );
//  cout << dist << endl;
  bbData d;
//  cout << "getting data " << endl;  
  d.sum = dist->Integral(1,256 );
  d.max = dist->GetBinContent(256);
  d.zero = dist->GetBinContent( 1 );
  dist->SetBinContent( 256,0);
  dist->SetBinContent( 1, 0);
  d.mean = dist->GetMean();
  d.stdev = dist->GetStdDev();
  d.prb0 = d.zero/d.sum;
  d.bad = d.zero + d.max;
  d.prbm = d.max/d.sum;
  d.sum1 = dist->Integral( d.mean - d.stdev, d.mean + d.stdev );
  d.sum2 = dist->Integral( d.mean - 2*d.stdev, d.mean + 2*d.stdev );
  d.sum3 = dist->Integral( d.mean - 3*d.stdev, d.mean + 3*d.stdev );
  d.prb1 = 1 - d.sum1/d.sum;
  d.prb2 = 1 - d.sum2/d.sum;
  d.prb3 = 1 - d.sum3/d.sum; 
 // cout << "returning" << endl;
  return d; 
} 

//-----------------------------------------------------------------------------------------------------------------------------------------
//----  next step, work in progress-------------------------------------------------------------------

pixChip getBadPixels( TH2D *mapfile, double thres ){

  double raw;
  pixChip bad;
  int badpix = 0;
  
  for( int row =RS; row < RE; row++ ){
    for( int col =CS; col < CE; col++){
      raw = mapfile->GetBinContent( row, col );
      if(  raw < thres ){
	badpix++;
	bad.setCell( badpix, row, col, 3 );

      }
    }
  }
  bads.setCount( badpix );
  return bad;
  
}

int  printBadCells( ofstream& myout, pixChip chip ){
  

  pixCell cell;
  int total = 0;

 // cout << "printing Bad Cells......." << endl;
  myout << "Chip" << myfillTo( 8, "Row") << myfillTo( 8, "Col") << myfillTo( 8, "Data") << endl;

  for( int i = 0; i < MAXPIXS; i++){
    cell = chip.getCell( i );
    if( cell.chip > -1 ){
    		myout << myfillTo( 3, cell.chip ) << myfillTo( 8, cell.row ) << myfillTo( 8, cell.col ) << myfillTo( 8, cell.data ) << endl; 
    		total++;
    	};
 	};

 // cout << " --------- End of List --------- " << endl;
  return total;
}

void getBadPixBBStats( string dirfile, string histfile ){

  TFile* direct = new TFile( strToChar( dirfile ) );
  TH2D* hist;
  direct->GetObject( strToChar( histfile ), hist );

  //    extract stats from histogram

 

  return;
}

//------------------------------------------------------------------------------------------------------------------------------------
//-----------------------------------------------------  start of scripts ------------------------------------------------------------
//-------------------------------  KU convention assumed for first section -----------------------------------------------------------
//------------------------------------------------------------------------------------------------------------------------------------
// --   scripts --  designed to loop through all chips in a module with minimal input
// --  assumed that root is ran from within the folder with the TFiles in question.
//------------------------------------------------------------------------------------------------------------------------------------

// returns bad for a chip if any pixles in the chip are below a threshold of 8
// on the pixel Alive test. llops through all chips on module

bool validpa( string module ){//tested

  string padirfile ( module + padir );
  string pasource("");
  cout << "opeaning in files" << endl;

  TFile *paInFile = new TFile( strToChar( padirfile ) );

  cout << paInFile;  

  ofstream out;
  openOutStream( module + paValidText,  out );
  out << " Valid Returns for PA level numbers:"<<endl;
  cout << " : creating plot files" << endl;
  TH2D *paHist;
  pixChip badcells;  


  bool result = true, moduleResult = true;
  int badFiles = 0;
  
  for( int i = 0; i < 16; i++ ){ 

    pasource = pasubdir + pafile.substr( 0,12 ) + intToStr( i ) + pafile.substr( 12 );
    paInFile->GetObject( strToChar( pasource ), paHist );
   
    out << paHist << "  " << pasource << " : ";
    //out << ": Checking values vs threshold : " ;

    result = pixAliveGood( paHist , badcells );
		moduleResult = moduleResult && result;
    if( result ) out << "Chip is good" << endl;
    else{ out << "Chip is Bad with "<< badcells.getCount() << " bad pix cells. " << endl;
    			badFiles++;
    }
		badcells.zeroChip();
    // badcells.printCellsWithDataOnChip( out );
    //    cout << result << endl;
  };


  out.close();
  if( moduleResult ) cout << "Module " << module << "  PA files are GOOD."<<endl;
  else cout <<" Modules " << module << " PixelAlive has " << badFiles << " Chips that are BAD."<<endl;  

  return result;

}

bool validxray( string module ){

  string xrdirfile ( module + xrdir );
  string xrsource("");
  cout << "opeaning in files" << endl;
  TFile *xrInFile = new TFile( strToChar( xrdirfile ) );
  cout << xrInFile;  
  ofstream out;


  openOutStream( module + xrValidText,  out );
  out << " Non-Zero Returns for XR level numbers:"<<endl;
  cout << " : creating plot files" << endl;

  TH2D *xrHist;
  pixChip badcells;  

  bool result = true;
  for( int i = 0; i < 16; i++ ){ 
    
    xrsource = xrsubdir + xrfile.substr( 0,6 ) + intToStr( i ) + xrfile.substr( 6 );
    cout << xrsource << endl;
    xrInFile->GetObject( strToChar( xrsource ), xrHist );
    out << xrHist << "  " << xrsource << " : ";
    result = xRayThreshold( xrHist , out, badcells ) && result;
    //printBadCells( out, badcells );

    //    cout << result << endl;
  };
  out.close();
  return result;
}

// compares bumpbond vs pixel alive map and returns a 4 value map
// it first uses a threshold valueof 8 on PA to determine if pixel good/bad
// it then set all pixels over 2 sigma on BB as bad, under good
// compares the result pixel by pixel and returns a new map that 
// shows if both bad, both good, or the two cases of only one good
// loops through all chips on module

void bbpacomp( string module  ){//tested
  

  string bbtestfile(""), padirect(""), patestfile("");
  string bbdirect(""), bbsource(""), pasource(""), title(""), outfile("");

  padirect = module + padir;
  string mainTitle( module + bbpaBadPixsText );
  ofstream out;  
  openOutStream( mainTitle, out );
  out << module << " BB vs PA Comparision Map" << endl;
  string outfile("");
  TH2D* hist;
  pixChip badcells;
  int total = 0;
  string title( module + "_BBBadPixelsList.txt");
  ofstream rout;
  openOutStream( title, rout );
  rout << "Bad BumpBond List : " << module << endl;
  rout << "Data value of 2 indicates bad bump bond" << endl;
  
  for( int chip = 0; chip < 16; chip++ ){    
    outfile = module + "_C" + intToStr( chip ); 

    bbdirect = module + bbdir.substr( 0, 5 ) + intToStr( chip ) + bbdir.substr( 5  );
    bbsource = bbsubdir + bbfile.substr( 0, 22 ) + intToStr( chip ) + bbfile.substr( 22 );//27
    pasource = pasubdir + pafile.substr( 0,12 ) + intToStr( chip ) + pafile.substr( 12 );
    out << "Chip : " + intToStr( chip ) << endl;
    hist = (TH2D*) compBBPAMap( padirect, bbdirect, pasource, bbsource );
    hist->SetNameTitle( strToChar( outfile ), "CompMap"); 
    TFile *outCompFile = new TFile( strToChar( module + cpdir ), "UPDATE" );  
    cout << "outfile is : " << outfile << ":" << outCompFile << endl;
    cout << "writing histogram file" << endl;
    hist->Write();
    outCompFile->Close();
    cout << "writing bad pix text file"<<endl;  
    //cout << "getting cells" << endl;
    // out << module << " BB vs PA Comparision Map" << endl;
    badcells = getBadBBPACompPixs( chip, hist, module, out );
    cout << "writing cells" << endl;
    total =  printBadCells( rout, badcells );
    rout << "C" << intToStr( chip ) << " Total bad bump bonds: " << total << endl;
  }


  out.close();
  rout.close();    string cpdirfile( module + cpdir );
  string xrdirfile( module + xrdir );

  string outfile( module + cpxrdir );
  string mainTitle( module + cpxrPixsStatsText );
  return;

}

// 	does same this as bbpacomp but uses the result of bbpacomp and
// 	the DAC test histograms and returns a 4 value comparision of the 
// 	bbpacomp result map and the DAC maps loops through all chips

void cpxrcomp( string module ){//tested
 
  string xrsource(""), cpsource("");  


  string cpdirfile( module + cpdir );
  string xrdirfile( module + xrdir );
  string outfile( module + cpxrdir );
  string textfile( module + cpxrPixsStatsText );

  ofstream out;  
  openOutStream( textfile, out );
  ofstream rout;
  openOutStream( module + badCPvsXRList, rout );
  cout << "Printing Bad Pixels for CP vs XR " << endl;
  rout << "List of bad pixs for cp vs xr comparison test " << module << endl;
  rout << "Data value of 1 indicates Cell was bad on Xray and Good on BumpBond and  PixelAlive." << endl;
  rout << "Data value of 2 indicates Cell was bad on BumpBond and PixelAlive and good on Xray." << endl;
  out << " CP vs XR Comparision Map" << endl;
  
  TH2D *hist;
  TFile *infile = new TFile( strToChar( xrdirfile ) ); 
  pixChip bads;
  TH2D* hist;
  
  int total = 0;
  
 
 for( int i = 0; i < 16; i++ ){ 
    cpsource = bbpacompmap + intToStr( i );
    xrsource = xrsubdir + xrfile.substr( 0,6 ) + intToStr( i ) + xrfile.substr( 6 );//6
    out << "Chip : " + intToStr( i ) << endl;
    hist =  (TH2D*) compXRCPMaps( cpdirfile, xrdirfile, cpsource, xrsource );
    hist->SetNameTitle( strToChar( xrdirfile.substr(0,8) + "_XRCP_Map" ) , "Comparison Map");  
    TFile *outCompFile = new TFile( strToChar( outfile ), "UPDATE" );  

    cout << "outfile is : " << outfile << ":" << outCompFile << endl;
    cout << "writing histogram file" << endl;
    hist->Write();

    outCompFile->Close();
    cout << "getting cells" << endl;
    bads = getBadCPXRCompPixs( i, hist, module, out ); 
    total = printBadCells( rout, bads );
    rout << "C" << intToStr( i ) << " Total bad pixs : " << total << endl; 

    cout << "writing bad pix text file"<<endl;  
//    cout << " returning"  << endl;
 }

  out.close(); 
  rout.close();
  return;
}


void xrhreff( string hreffdirfile ){
  
  string pasource("");
  TH2D *hist;
  TFile *infile = new TFile( strToChar( hreffdirfile + ".root" ) );
  cout << infile << endl;;	

  double mean, stderr;
  ofstream out;  

  openOutStream( hreffdirfile + ".txt" , out );
  //out << module << " Chip HReff " << distance << "cm " << endl;
  cout << "getting HReff Stats " << endl;
  //ofstream rout;
  //openOutStream( module + badCPvsXRList, rout );
  //rout << "--list of bad pixs for cp vs xr comparison test" << endl;
  // cout.precision( 4 );
  for( int i = 0; i < 16; i++ ){ 
    pasource = pasubdir + pafile.substr( 0,12 ) + intToStr( i ) + pafile.substr( 12 );
    cout << pasource << endl;
    infile->GetObject( strToChar( pasource ), hist );
    cout << hist<< endl;
    out << myfillTo( 5, "C" + intToStr( i ) + " : " );
    mean = myGetMean( hist );
    stderr = myGetStdErr( hist, mean );
    out <<  mean   << "\t  +/- " << stderr << endl;
  }

  out.close(); 
  //  rout.close();
  return;
}

// takes the same histogram from two diffrent modules and compares them 
// to see if the are the same -- used for repeat runs of same module


void mmcomp( string amodule, string bmodule, string dir, string mapfile ){//tested
  
  string cp1dirfile(""), cp2dirfile("");
  string cp1source(""), cp2source("");
  
  cp1dirfile = amodule + "/" + amodule + dir;
  cp2dirfile = bmodule + "/" + bmodule + dir;
  
  cp1source = amodule + mapfile;
  cp2source =  bmodule + mapfile;
 
  compMapToMap( cp1dirfile, cp2dirfile, cp1source, cp2source, amodule, bmodule );
  return;
}

// same as above for all chips on a module

void multimmcomp( string amodule, string bmodule, string dir, string mapfile  ){//tested
  
  string cp1dirfile(""), cp2dirfile("");
  string cp1source(""), cp2source("");
  
  cp1dirfile = amodule + "/" + amodule + dir;
  cp2dirfile = bmodule + "/" + bmodule + dir;
  
  for( int i = 0; i < 16; i++ ){ 
    
    cp1source = amodule + mapfile.substr( 0, 5 ) + intToStr( i ) + mapfile.substr( 5 );//5
    cp2source =  bmodule + mapfile.substr( 0,5 ) + intToStr( i ) + mapfile.substr( 5 );//5
    compMapToMap( cp1dirfile, cp2dirfile, cp1source, cp2source, amodule, bmodule );
    
  }

  return;
}

//  pulls good vs bad pixels and distributions of data for the BumpBond test
// for all chips on module.  assumes each chip has its own TFile

void bbstats( string bbdirfile, int chip ){//tested  --  where there is one chip per dir file
  
  string tempdirfile(""), tempfile("");
  bbData data;
  string cpdirfile(""), xrdirfile("");
  string titlestr3("; >3Sigma; num chips");
  string titlestr2("; >2Sigma; num chips");
  string titlestr1("; >1Sigma; num chips");
 
  cout << "setting up files:" << endl;
  TH1D *sigma3Hist = new TH1D( ">3sigma",strToChar( module + titlestr3 ), 150, 0, 2000);
  TH1D *sigma2Hist = new TH1D( ">2sigma", strToChar( module + titlestr2 ), 200, 0, 2000);
  TH1D *sigma1Hist = new TH1D( ">1sigma", strToChar( module + titlestr1 ), 200, 0, 2000);
  
  string outputfilename = module + bbDistroText;

  cout << "opeaning out file:"<<endl;
  ofstream out;
  openOutStream( outputfilename, out);		
  
  cout << "Fromating out file" << endl;
  out <<  outputfilename << endl;
 	out << "Chip" << myfillTo( 10, "BadPixs") << myfillTo(5,"Mean") << myfillTo(8, "StDev") <<  myfillTo(8,"=0");
 	out << myfillTo( 9, ">1Sig") << myfillTo(8,">2Sig") << myfillTo( 8, ">3Sig") << myfillTo( 7, "=Max") << endl;
  
  string outfile("");
  outfile = module + cpxrdir;
  cout << " runnign loop to count bad pixels" << endl;
  tempfile = bbdistfile.substr(0, 27) + intToStr( chip ) + bbdistfile.substr( 27 );
  //		 cout << tempdirfile << ":" << tempfile << endl;

  data = getBBStats( tempdirfile, bbsubdir, tempfile );
  sigma3Hist->Fill( PIXCELLS - data.sum3 );
  sigma2Hist->Fill( PIXCELLS - data.sum2 );
  sigma1Hist->Fill( PIXCELLS - data.sum1 );
  // 		cout << data.mean<<endl;
    
  out.precision(5);
  out << myFillAfter(8,  "  C" + intToStr( i )  );
  out << myFillAfter(8, data.bad );
  out << myFillAfter(8, data.mean);
  out << myFillAfter(8, data.stdev);
  out << myFillAfter(8, data.zero );				//prb0*100 << "(" << zero << ")";
  out << myFillAfter(8, sum - data.sum1 );	//prb1*100 << "(" << sum1 << ")"; 
  out << myFillAfter(8, sum - data.sum2 );	//prb2*100 << "(" << sum2 << ")";
  out << myFillAfter(8, sum - data.sum3 );	//prb3*100 << "(" << sum3 << ")";
  out << myFillAfter(8, data.max) << endl;  //prbm*100 << "(" << max << ")" << endl;


  cout << "saving histograms" << endl;
  string outfile = module + "_BBDistros.root";
  TFile *outCompFile = new TFile( strToChar( outfile ), "UPDATE" );  
  cout << "outfile is : " << outfile << ":" << outCompFile << endl;

  cout << "writing histogram file" << endl;
  sigma3Hist->Write();
  sigma2Hist->Write();
  sigma1Hist->Write();
  outCompFile->Close();
  out.close();
 // cout << " returning"  << endl;

  //	sigma3Hist->Draw();
  //    sigma2Hist->Draw();
  //	sigma1Hist->Draw();
  return;
}


void bbstats( string bbdirfile ){//tested -- where there is one dir file for all chips
  																// NO suffex on file name
  string tempfile("");
  bbData data;
  string titlestr3("; >3Sigma; num chips");
  string titlestr2("; >2Sigma; num chips");
  string titlestr1("; >1Sigma; num chips");
 
  cout << "setting up files:" << endl;
  TH1D *sigma3Hist = new TH1D( ">3sigma",strToChar( module + titlestr3 ), 150, 0, 1500);
  TH1D *sigma2Hist = new TH1D( ">2sigma", strToChar( module + titlestr2 ), 200, 0, 400);
  TH1D *sigma1Hist = new TH1D( ">1sigma", strToChar( module + titlestr1 ), 200, 0, 400);
  
  string outputfilename( bbdirfile + ".txt" );

  cout << "opeaning out file:"<<endl;

  ofstream out;
  openOutStream( outputfilename, out);		
  

  cout << "Fromating out file" << endl;
  out <<  outputfilename << endl;
  out << "Chip" << myfillTo( 10, "BadPixs") << myfillTo(5,"Mean") << myfillTo(8, "StDev") <<  myfillTo(8,"=0");
  out << myfillTo( 9, ">1Sig") << myfillTo(8,">2Sig") << myfillTo( 8, ">3Sig") << myfillTo( 7, "=Max") << endl;
  

  cout << " runnign loop to count bad pixels" << endl;
  for( int i = 0; i < 16; i++ ){ 
    tempfile = bbdistfile.substr(0, 27) + intToStr( i ) + bbdistfile.substr( 27 );
    //		 cout << tempdirfile << ":" << tempfile << endl;
    data = getBBStats( bbdirfile + ".root", tempfile );
    sigma3Hist->Fill( PIXCELLS - data.sum3 );
    sigma2Hist->Fill( PIXCELLS - data.sum2 );
    sigma1Hist->Fill( PIXCELLS - data.sum1 );
    // 		cout << data.mean<<endl;
    
    out.precision(5);
    out << myFillAfter(8,  "  C" + intToStr( i )  );
    out << myFillAfter(8, data.bad );
    out << myFillAfter(8, data.mean);
    out << myFillAfter(8, data.stdev);
    out << myFillAfter(8, data.zero );			//prb0*100 << "(" << zero << ")";
    out << myFillAfter(8, sum - data.sum1 );	        //prb1*100 << "(" << sum1 << ")"; 
    out << myFillAfter(8, sum - data.sum2 );	        //prb2*100 << "(" << sum2 << ")";
    out << myFillAfter(8, sum - data.sum3 );	        //prb3*100 << "(" << sum3 << ")";
    out << myFillAfter(8, data.max) << endl;         //prbm*100 << "(" << max << ")" << endl;

  }	


  cout << "saving histograms" << endl;
  string outfile = module + "_BBDistros.root";
  TFile *outCompFile = new TFile( strToChar( outfile ), "UPDATE" );  
  cout << "outfile is : " << outfile << ":" << outCompFile << endl;
  cout << "writing histogram file" << endl;
  sigma3Hist->Write();
  sigma2Hist->Write();

  sigma1Hist->Write();
  outCompFile->Close();
  out.close();
//  cout << " returning"  << endl;

  //	sigma3Hist->Draw();
  //    sigma2Hist->Draw();
  //	sigma1Hist->Draw();
  return;
}


void bbstatsAutoRun( string module ){//tested
  

  string tempdirfile(""), tempfile("");
  bbData data;
  string titlestr3("; >3Sigma; num chips");
  string titlestr2("; >2Sigma; num chips");
  string titlestr1("; >1Sigma; num chips");
 
  cout << "setting up files:" << endl;
  TH1D *sigma3Hist = new TH1D( ">3sigma",strToChar( module + titlestr3 ), 150, 0, 1500);
  TH1D *sigma2Hist = new TH1D( ">2sigma", strToChar( module + titlestr2 ), 200, 0, 400);
  TH1D *sigma1Hist = new TH1D( ">1sigma", strToChar( module + titlestr1 ), 200, 0, 400);
  
  string outputfilename = module + bbDistroText;

  cout << "opeaning out file:"<<endl;
  ofstream out;
  openOutStream( outputfilename, out);		
  
  cout << "Fromating out file" << endl;
  out <<  outputfilename << endl;
  out << "Chip" << myfillTo( 10, "BadPixs") << myfillTo(5,"Mean") << myfillTo(8, "StDev") <<  myfillTo(8,"=0");
  out << myfillTo( 9, ">1Sig") << myfillTo(8,">2Sig") << myfillTo( 8, ">3Sig") << myfillTo( 7, "=Max") << endl;
  cout << " runnign loop to count bad pixels" << endl;
  for( int i = 0; i < 16; i++ ){ 
    tempdirfile  = module + bbdir.substr( 0, 5 ) + intToStr( i ) + bbdir.substr( 5 );
    tempfile = bbdistfile.substr(0, 27) + intToStr( i ) + bbdistfile.substr( 27 );
    //		 cout << tempdirfile << ":" << tempfile << endl;
    data = getBBStats( tempdirfile, tempfile );
    sigma3Hist->Fill( PIXCELLS - data.sum3 );
    sigma2Hist->Fill( PIXCELLS - data.sum2 );
    sigma1Hist->Fill( PIXCELLS - data.sum1 );
    // 		cout << data.mean<<endl;
    
    out.precision(5);
    out << myFillAfter(8,  "  C" + intToStr( i )  );
    out << myFillAfter(8, data.bad );
    out << myFillAfter(8, data.mean);
    out << myFillAfter(8, data.stdev);
    out << myFillAfter(8, data.zero );			//prb0*100 << "(" << zero << ")";
    out << myFillAfter(8, data.sum - data.sum1 );	        //prb1*100 << "(" << sum1 << ")"; 
    out << myFillAfter(8, data.sum - data.sum2 );	        //prb2*100 << "(" << sum2 << ")";
    out << myFillAfter(8, data.sum - data.sum3 );	        //prb3*100 << "(" << sum3 << ")";
    out << myFillAfter(8, data.max) << endl;         //prbm*100 << "(" << max << ")" << endl;

  }	

  cout << "saving histograms" << endl;
  string outfile = module + "_BBDistros.root";
  TFile *outCompFile = new TFile( strToChar( outfile ), "UPDATE" );  
  cout << "outfile is : " << outfile << ":" << outCompFile << endl;
  cout << "writing histogram file" << endl;
  sigma3Hist->Write();
  sigma2Hist->Write();
  sigma1Hist->Write();
  outCompFile->Close();
  out.close();
//  cout << " returning"  << endl;

  //	sigma3Hist->Draw();
  //    sigma2Hist->Draw();
  //	sigma1Hist->Draw();
  return;
}

// runs all four base comparision tests on a single module

void runcomptests( string module ){//tested

  cout << "Runing BB Stats ___________________________________________________" << endl;
  bbstatsAutoRun( module );
  cout << "Running Valid PA __________________________________________________" << endl;
  validpa( module );
  cout << "Runining BB vs PA comparision______________________________________" << endl;
  bbpacomp( module );
  cout << "Running CP vs XR comparision_______________________________________" <<endl;
 	cpxrcomp( module );
 	cout << "Comparison Tests Completed_________________________________________" << endl;
  return; 
}


//---------------------------------------------------------------------------------------------------------------------
//---- Generic scripts to run BumpBond vs PixelAlive ------------------------------------------------------------------
//---------------------------------------------------------------------------------------------------------------------

// bumpbond directory and pixel alive directory files ( .root files ) must be in same directory the script is ran from
// bbdirname and padirbname are the name of the TFiles generated by pxar.  If additional subdirectories have been added 
// to the directory files then specify in bbsubfolder and pasubfolder.  Chip is the chip number that you want to 
// compare the Bumpbond and PixelAlive map histograms for.

void comparebbvspa( string bbdirname, string padirname, int chip ){

  comparebbvspa( bbdirname, "", padirname, "", chip );
  return;
}

void comparebbvspa( string bbdirname, string bbsubfolder, string padirname, string pasubfolder, int chip ){
 
  string bbsource(""), pasource("");
  string module( genericBBvsPAModuleName + intToStr( chip ) );
  
  ofstream out;  
  openOutStream( genericBBvsPAText, out );
  out << " BB vs PA Map Comparision Info" << endl;
 
  bbsource = bbsubdir + bbsubfolder + bbfile.substr( 0, 22 ) + intToStr( chip ) + bbfile.substr( 22 );
  pasource  = pasubdir + pasubfolder + pafile.substr( 0,12 ) + intToStr( chip ) + pafile.substr( 12 );
  compBBPAMap( chip, padirname, bbdirname, pasource, bbsource, module, out );
  out.close();
  return;
}
